#![deny(warnings)]
#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`MyStruct`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"MyStruct\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"allOf\": ["]
#[doc = "    {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"a\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"b\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"mysecondtag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"mysecondtag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"c\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"mysecondtag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"mysecondtag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"d\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum MyStruct {
    Variant0(MyStructVariant0),
    Variant1(MyStructVariant1),
}
impl ::std::convert::From<&Self> for MyStruct {
    fn from(value: &MyStruct) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<MyStructVariant0> for MyStruct {
    fn from(value: MyStructVariant0) -> Self {
        Self::Variant0(value)
    }
}
impl ::std::convert::From<MyStructVariant1> for MyStruct {
    fn from(value: MyStructVariant1) -> Self {
        Self::Variant1(value)
    }
}
#[doc = "`MyStructVariant0`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"allOf\": ["]
#[doc = "    {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"a\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"b\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"required\": ["]
#[doc = "        \"mysecondtag\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"mysecondtag\": {"]
#[doc = "          \"type\": \"string\","]
#[doc = "          \"enum\": ["]
#[doc = "            \"c\""]
#[doc = "          ]"]
#[doc = "        }"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"not\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"format\": \"uint64\","]
#[doc = "        \"minimum\": 0.0,"]
#[doc = "        \"required\": ["]
#[doc = "          \"mysecondtag\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"mysecondtag\": {"]
#[doc = "            \"type\": \"string\","]
#[doc = "            \"enum\": ["]
#[doc = "              \"d\""]
#[doc = "            ]"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum MyStructVariant0 {
    Variant0(MyStructVariant0Variant0),
    Variant1(MyStructVariant0Variant1),
}
impl ::std::convert::From<&Self> for MyStructVariant0 {
    fn from(value: &MyStructVariant0) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<MyStructVariant0Variant0> for MyStructVariant0 {
    fn from(value: MyStructVariant0Variant0) -> Self {
        Self::Variant0(value)
    }
}
impl ::std::convert::From<MyStructVariant0Variant1> for MyStructVariant0 {
    fn from(value: MyStructVariant0Variant1) -> Self {
        Self::Variant1(value)
    }
}
#[doc = "`MyStructVariant0Variant0`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"allOf\": ["]
#[doc = "    {},"]
#[doc = "    {"]
#[doc = "      \"allOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"mysecondtag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"mysecondtag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"c\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"a\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"not\": {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"format\": \"uint64\","]
#[doc = "            \"minimum\": 0.0,"]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"b\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"not\": {"]
#[doc = "        \"allOf\": ["]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"mysecondtag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"mysecondtag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"c\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"format\": \"uint64\","]
#[doc = "            \"minimum\": 0.0,"]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"b\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"not\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"required\": ["]
#[doc = "                \"myfirsttag\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"myfirsttag\": {"]
#[doc = "                  \"type\": \"string\","]
#[doc = "                  \"enum\": ["]
#[doc = "                    \"a\""]
#[doc = "                  ]"]
#[doc = "                }"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        ]"]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
#[serde(deny_unknown_fields)]
pub enum MyStructVariant0Variant0 {}
impl ::std::convert::From<&Self> for MyStructVariant0Variant0 {
    fn from(value: &MyStructVariant0Variant0) -> Self {
        value.clone()
    }
}
#[doc = "`MyStructVariant0Variant1`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"allOf\": ["]
#[doc = "    {},"]
#[doc = "    {"]
#[doc = "      \"allOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"mysecondtag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"mysecondtag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"c\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"b\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"not\": {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"a\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"not\": {"]
#[doc = "        \"allOf\": ["]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"mysecondtag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"mysecondtag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"c\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"a\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"not\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"format\": \"uint64\","]
#[doc = "              \"minimum\": 0.0,"]
#[doc = "              \"required\": ["]
#[doc = "                \"myfirsttag\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"myfirsttag\": {"]
#[doc = "                  \"type\": \"string\","]
#[doc = "                  \"enum\": ["]
#[doc = "                    \"b\""]
#[doc = "                  ]"]
#[doc = "                }"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        ]"]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
#[serde(deny_unknown_fields)]
pub enum MyStructVariant0Variant1 {}
impl ::std::convert::From<&Self> for MyStructVariant0Variant1 {
    fn from(value: &MyStructVariant0Variant1) -> Self {
        value.clone()
    }
}
#[doc = "`MyStructVariant1`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"allOf\": ["]
#[doc = "    {"]
#[doc = "      \"oneOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"a\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"b\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"format\": \"uint64\","]
#[doc = "      \"minimum\": 0.0,"]
#[doc = "      \"required\": ["]
#[doc = "        \"mysecondtag\""]
#[doc = "      ],"]
#[doc = "      \"properties\": {"]
#[doc = "        \"mysecondtag\": {"]
#[doc = "          \"type\": \"string\","]
#[doc = "          \"enum\": ["]
#[doc = "            \"d\""]
#[doc = "          ]"]
#[doc = "        }"]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"not\": {"]
#[doc = "        \"type\": \"object\","]
#[doc = "        \"required\": ["]
#[doc = "          \"mysecondtag\""]
#[doc = "        ],"]
#[doc = "        \"properties\": {"]
#[doc = "          \"mysecondtag\": {"]
#[doc = "            \"type\": \"string\","]
#[doc = "            \"enum\": ["]
#[doc = "              \"c\""]
#[doc = "            ]"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
#[serde(untagged)]
pub enum MyStructVariant1 {
    Variant0(MyStructVariant1Variant0),
    Variant1(MyStructVariant1Variant1),
}
impl ::std::convert::From<&Self> for MyStructVariant1 {
    fn from(value: &MyStructVariant1) -> Self {
        value.clone()
    }
}
impl ::std::convert::From<MyStructVariant1Variant0> for MyStructVariant1 {
    fn from(value: MyStructVariant1Variant0) -> Self {
        Self::Variant0(value)
    }
}
impl ::std::convert::From<MyStructVariant1Variant1> for MyStructVariant1 {
    fn from(value: MyStructVariant1Variant1) -> Self {
        Self::Variant1(value)
    }
}
#[doc = "`MyStructVariant1Variant0`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"allOf\": ["]
#[doc = "    {},"]
#[doc = "    {"]
#[doc = "      \"allOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"mysecondtag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"mysecondtag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"d\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"a\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"not\": {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"format\": \"uint64\","]
#[doc = "            \"minimum\": 0.0,"]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"b\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"not\": {"]
#[doc = "        \"allOf\": ["]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"format\": \"uint64\","]
#[doc = "            \"minimum\": 0.0,"]
#[doc = "            \"required\": ["]
#[doc = "              \"mysecondtag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"mysecondtag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"d\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"format\": \"uint64\","]
#[doc = "            \"minimum\": 0.0,"]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"b\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"not\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"required\": ["]
#[doc = "                \"myfirsttag\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"myfirsttag\": {"]
#[doc = "                  \"type\": \"string\","]
#[doc = "                  \"enum\": ["]
#[doc = "                    \"a\""]
#[doc = "                  ]"]
#[doc = "                }"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        ]"]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
#[serde(deny_unknown_fields)]
pub enum MyStructVariant1Variant0 {}
impl ::std::convert::From<&Self> for MyStructVariant1Variant0 {
    fn from(value: &MyStructVariant1Variant0) -> Self {
        value.clone()
    }
}
#[doc = "`MyStructVariant1Variant1`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"allOf\": ["]
#[doc = "    {},"]
#[doc = "    {"]
#[doc = "      \"allOf\": ["]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"mysecondtag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"mysecondtag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"d\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"object\","]
#[doc = "          \"format\": \"uint64\","]
#[doc = "          \"minimum\": 0.0,"]
#[doc = "          \"required\": ["]
#[doc = "            \"myfirsttag\""]
#[doc = "          ],"]
#[doc = "          \"properties\": {"]
#[doc = "            \"myfirsttag\": {"]
#[doc = "              \"type\": \"string\","]
#[doc = "              \"enum\": ["]
#[doc = "                \"b\""]
#[doc = "              ]"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"not\": {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"a\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    {"]
#[doc = "      \"not\": {"]
#[doc = "        \"allOf\": ["]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"format\": \"uint64\","]
#[doc = "            \"minimum\": 0.0,"]
#[doc = "            \"required\": ["]
#[doc = "              \"mysecondtag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"mysecondtag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"d\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"type\": \"object\","]
#[doc = "            \"required\": ["]
#[doc = "              \"myfirsttag\""]
#[doc = "            ],"]
#[doc = "            \"properties\": {"]
#[doc = "              \"myfirsttag\": {"]
#[doc = "                \"type\": \"string\","]
#[doc = "                \"enum\": ["]
#[doc = "                  \"a\""]
#[doc = "                ]"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          },"]
#[doc = "          {"]
#[doc = "            \"not\": {"]
#[doc = "              \"type\": \"object\","]
#[doc = "              \"format\": \"uint64\","]
#[doc = "              \"minimum\": 0.0,"]
#[doc = "              \"required\": ["]
#[doc = "                \"myfirsttag\""]
#[doc = "              ],"]
#[doc = "              \"properties\": {"]
#[doc = "                \"myfirsttag\": {"]
#[doc = "                  \"type\": \"string\","]
#[doc = "                  \"enum\": ["]
#[doc = "                    \"b\""]
#[doc = "                  ]"]
#[doc = "                }"]
#[doc = "              }"]
#[doc = "            }"]
#[doc = "          }"]
#[doc = "        ]"]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
#[serde(deny_unknown_fields)]
pub enum MyStructVariant1Variant1 {}
impl ::std::convert::From<&Self> for MyStructVariant1Variant1 {
    fn from(value: &MyStructVariant1Variant1) -> Self {
        value.clone()
    }
}
fn main() {}
